FROM php:8.0.2-cli

RUN docker-php-source extract \
	&& mkdir -p /usr/src/php/ext/fiber \
	&& curl -fsSL "https://github.com/amphp/ext-fiber/archive/master.tar.gz" | tar xvz -C /usr/src/php/ext/fiber --strip 1 \
	&& docker-php-ext-install fiber \
	&& docker-php-source delete
