#!/bin/bash
echo "DOCKER_TAG=${DOCKER_TAG}"
docker build . \
	-t "${PHP_VERSION}-${DOCKER_TAG}_fiber-${UPSTREAM_COMMIT:0:7}" \
	-t "${DOCKER_TAG}_fiber-latest" \
	--build-arg PHP_VERSION=$PHP_VERSION \
	--build-arg PHP_TAG=$DOCKER_TAG \
	--build-arg UPSTREAM_COMMIT=$UPSTREAM_COMMIT
