#!/bin/bash
export PHP_VERSION=${SOURCE_TAG%-*}
export UPSTREAM_COMMIT=${SOURCE_TAG#*-}
docker build . \
	-t "${PHP_VERSION}-${DOCKER_TAG}_fiber-${UPSTREAM_COMMIT:0:7}" \
	-t "${DOCKER_TAG}_fiber-latest" \
	--build-arg \
		PHP_VERSION=$PHP_VERSION \
		PHP_TAG=$DOCKER_TAG \
		UPSTREAM_COMMIT=$UPSTREAM_COMMIT
